version: 1
build:
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 200000000timpi
  - 200000000000utimpi
- name: bob
  coins:
  - 100000000timpi
  - 200000000000utimpi
- name: tim
  coins:
  - 100000000timpi
  - 100000000000utimpi
- name: jane
  coins:
  - 100000000timpi
faucet:
  name: bob
  coins:
  - 5timpi
  - 100000000utimpi
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
genesis:
  app_state:
    gov:
      deposit_params:
        max_deposit_period: 172800000000ns
        min_deposit:
        - denom: utimpi
        - amount: "4000000000"
      voting_params:
        voting_period: 172800000000ns
    mint:
      params:
        mint_denom: utimpi
    staking:
      params:
        bond_denom: utimpi
validators:
- name: tim
  bonded: 10000000000utimpi
