version: 1
accounts:
- name: alice
  coins: 
  - 200000000timpi
  - 200000000000utimpi
- name: bob
  coins: 
  - "100000000timpi"
  - "200000000000utimpi"
- name: tim
  coins:
  - "100000000timpi"
  - "100000000000utimpi"
- name: jane
  coins: 
  - "100000000timpi"
validators:
- name: alice
  bonded: "10000000000utimpi"
- name: tim
  bonded: "10000000000utimpi"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: 
  - 5timpi
  - 100000000utimpi
genesis:
  chain_id: "timpitest"
  app_state:
    staking:
      params:
        bond_denom: "utimpi"
    mint:
      params:
        mint_denom: "utimpi"
    gov:
      deposit_params:
        min_deposit: 
        - denom: "utimpi"
        - amount: "4000000000"
        max_deposit_period: "172800000000ns"
      voting_params:
        voting_period: "172800000000ns"

